@BidCalculator_HostAddress = http://localhost:5238

POST {{BidCalculator_HostAddress}}/BidCars/api/pricecalculation/
Accept: application/json
Content-Type: application/json

{
  "basePrice": 398,
  "vehicleType": "Common"
}

###
